name: LLoyd Webhook Caller
description: Used by LeafLink repositories to call LLoyd webhooks when events occur within a GitHub Action workflow
inputs:
  webhook_url:
    description: Webhook URL to call
    required: true
  webhook_token:
    description: Authentication bearer token for the webhook
    required: true
  event:
    description: The type of event that has occurred
    required: true
  repo:
    description: The name of the GitHub repository the Action is being run from
    default: invalid
  tag:
    description: The git tag corresponding to the Action run
    default: invalid
runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/call-webhook.sh \
          --webhook-url ${{ inputs.webhook_url }} \
          --webhook-token ${{ inputs.webhook_token }} \
          --event ${{ inputs.event }} \
          --repo ${{ inputs.repo }} \
          --tag ${{ inputs.tag }}
      shell: bash
